import React from 'react';
import './footer.css';

function Footer() {
    return (
        <footer className="footer">©2026 Whitney Yuen.&nbsp; Coded in Visual Studio Code. Built with&nbsp;<span className="text-blue-500">React</span>&nbsp;&&nbsp;<span className="text-purple-500">Gemini</span>. Photo generated by&nbsp;<span className="text-green-500">AIEASE</span>. All rights reserved.</footer>
    )
}

export default Footer;
