import React from 'react';
import './footer.css';

function Footer() {
    return (
        <footer className="footer">©2025 &nbsp;&nbsp; Coded in Visual Studio Code. Built with React.js. Photo generated by AIEASE.</footer>
    )
}

export default Footer;
